core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from register import views as v
from quiz import views 


urlpatterns = [
#ADMIN AND HOME URLS
    path('admin/', admin.site.urls),
    path('login/', v.login, name='login'),
    path("", views.home, name = "home"),
    path('', include('django.contrib.auth.urls')),
    path("home/",views.home, name = "home"),
    path("about/",views.about, name = "about"),
    path("faq/",views.faq, name = "faq"),
    path("progs/",views.progs, name = "progs"),
    path("howto/",views.howto, name = "howto"),
    path("privacy/",views.privacy, name = "privacy"),
    path("terms/",views.terms, name = "terms"),
    path("output/",views.output, name = "output"),
    path("pursueproject/",views.pursueproject, name = "pursueproject"),
    path('pdf/', v.generate_apostille, name='generate_pdf'),
    path('view/pdf/', v.view_apostille, name='view_pdf'),
    path('certificate/', v.generate_certificate, name='generate_certificate'),
    path('view/certificate/', v.view_certificate, name='view_certificate'),


#PROGS
    path("progs/CE",views.CE, name = "CE"),
    path("progs/ECE",views.ECE, name = "ECE"),
    path("progs/ME",views.ME, name = "ME"),
    path("progs/EE",views.EE, name = "EE"),



#PROFILE URLS
    path("register/", v.register, name = "register"),
    path("profile/<str:pk>/", v.profile, name = "profile"),
    path("results/<str:pk>/", v.results, name = "results"),
    path("profile/edit/<str:pk>/", v.edit, name = "edit"),


#PASSWORD URLS
    path("password/", v.change_password, name = 'change_password'),

    path("password_reset/",auth_views.PasswordResetView.as_view(
        template_name = 'password_reset_form.html', 
        success_url = reverse_lazy("password_reset_done"),
        email_template_name = 'password_reset_email.html'),
        name = "password_reset"),
    
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name = 'registration/password_reset_done.html'),
        name = "password_reset_done"),

    path("password_reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name = 'registration/password_reset_confirm.html',
        success_url = reverse_lazy("password_reset_complete")), 
        name = "password_reset_confirm"),

    # path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='password_reset_confirm.html'),
    #     name="password_reset_confirm"),

    path("password_reset/complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name = 'registration/password_reset_complete.html'),
        name = "password_reset_complete"),

#python -m smtpd -n -c DebuggingServer localhost:1025
##^this is for setting up the email server for password reset, run in a separate workspace

#QUIZ URL
    path(r'exam/', include('quiz.urls')),

#INPUT GRADES URL
    path('', include('inputshs.urls')),
    

#ASSESSMENT URL
    path('', include('likert.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .validators import alphabetic

class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(_('first name'), max_length=150, blank=True, validators=[alphabetic])
    last_name = models.CharField(_('last name'), max_length=150, blank=True, validators=[alphabetic])
    date_created = models.DateTimeField(auto_now_add = True)
    grades_done = models.BooleanField(default=False)
    exam_done = models.BooleanField(default=False)
    assessment_done = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    hash = models.CharField(null=True, blank=True, max_length=64)
    program = models.CharField(null=True, blank=True, max_length=64)
    program_value = models.CharField(null=True, blank=True, max_length=64)
    school = models.CharField(null=True, blank=True, max_length=64)

class Results(models.Model):
    user = models.ForeignKey(User, related_name = 'results', on_delete = models.CASCADE)
    CE_grades = models.FloatField(default=0,  null=True, blank=True)
    ECE_grades = models.FloatField(default=0,  null=True, blank=True)
    EE_grades = models.FloatField(default=0,  null=True, blank=True)
    ME_grades = models.FloatField(default=0,  null=True, blank=True)
    
    GE_exam= models.FloatField(default=0,  null=True, blank=True)
    CE_exam= models.FloatField(default=0,  null=True, blank=True)
    ECE_exam = models.FloatField(default=0,  null=True, blank=True)
    EE_exam = models.FloatField(default=0,  null=True, blank=True)
    ME_exam = models.FloatField(default=0,  null=True, blank=True)

    GE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    CE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    ECE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    EE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    ME_exam_done = models.BooleanField(default=False, null=True, blank=True)

    CE_assessment = models.FloatField(default=0,  null=True, blank=True)
    ECE_assessment = models.FloatField(default=0,  null=True, blank=True)
    EE_assessment = models.FloatField(default=0,  null=True, blank=True)
    ME_assessment = models.FloatField(default=0,  null=True, blank=True)
    
    class Meta:
            verbose_name_plural = ('Results')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def result_create(sender, instance=None, created=False, **kwargs):
        if created:
            Results.objects.create(user=instance,)



#gawa ng custom user model na boolean field, if true ang "is done with test/grade/quiz", redirect to home

register/views.py
import sys
import inspect
from django.contrib import auth, messages
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm, AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied, ValidationError
from django.http.response import HttpResponse
from django.shortcuts import render, redirect

from Naked.toolshed.shell import execute_js, muterun_js

from django.template.loader import render_to_string
from weasyprint import HTML, CSS
import tempfile

from inputshs.models import Grade
from register.models import Results, User

from .forms import RegisterForm, EditProfileForm, LoginForm, PasswordChangingForm
from .utils import render_to_pdf

# Create your views here.

def retrieve_name(var):
    callers_local_vars = inspect.currentframe().f_back.f_locals.items()
    return [var_name for var_name, var_val in callers_local_vars if var_val == var]


@login_required
def generate_apostille(request):
    """Generate pdf."""
    # Model data
    user = request.user
    user_results = Results.objects.filter(user_id=user.id)
    individual_result = user_results.first()
    grade = exam_scores = results = context = None

    if user.assessment_done and user.exam_done and user.grades_done:
        try:
            grade = Grade.objects.filter(user=request.user).first()
        except ObjectDoesNotExist:
            grade = None

        def get_score(course):
            try:
                score = user.sitting_set.filter(quiz__title=course).first().current_score
            except (TypeError, AttributeError):
                score = ''
            return score

        GE_score = get_score(course='General Engineering')
        CE_score = get_score(course='Civil Engineering')
        ECE_score = get_score(course='Electronics Engineering')
        EE_score = get_score(course='Electrical Engineering')
        ME_score = get_score(course='Mechanical Engineering')
        exam_scores = [GE_score, CE_score, ECE_score, EE_score, ME_score]

        try:
            results_unsorted = []
            programs = []
            Civil_Engineering =  "{:.2%}".format(individual_result.CE_grades + individual_result.CE_assessment + individual_result.CE_exam)
            Electronics_Engineering =  "{:.2%}".format(individual_result.ECE_grades + individual_result.ECE_assessment + individual_result.ECE_exam)
            Electrical_Engineering =  "{:.2%}".format(individual_result.EE_grades + individual_result.EE_assessment + individual_result.EE_exam)
            Mechanical_Engineering =  "{:.2%}".format(individual_result.ME_grades + individual_result.ME_assessment + individual_result.ME_exam)
            results_unsorted.extend([Civil_Engineering, Electronics_Engineering, Electrical_Engineering, Mechanical_Engineering])
            results = sorted(results_unsorted, reverse=True)
            
            for i in range(len(results)):
                programs.append(str(retrieve_name(results[i]))[2:-2].replace("_", " "))

        except ObjectDoesNotExist:
            results = None

        if not user.program:
            print('test')
            id = User.objects.filter(pk=user.id).values_list('id',flat=True).first()
            obj = User.objects.get(pk=id)
            obj.program = programs[0]
            obj.program_value = results[0]
            obj.save()


        context = {"user": user, "grade": grade, "exam_scores": exam_scores, "results": results, 'programs': programs}

        # Rendered
        html_string = render_to_string('results.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri())
        css = CSS('register/static/assets/bootstrap/css/foroutput.css')
        html.write_pdf('nem/results_pdf/' + 'PURSUE_results.pdf', stylesheets=[css], presentational_hints=True)
        result = html.write_pdf(stylesheets=[css], presentational_hints=True)
        filename = f"{user.username}_Recommendation.pdf"
        
        # Creating http response
        content = "attachment; filename=%s" %(filename)
        response = HttpResponse(content_type='application/pdf;')
        response['Content-Disposition'] = content
        response['Content-Transfer-Encoding'] = 'binary'

        with tempfile.NamedTemporaryFile(delete=True) as output:
            output.write(result)
            output.flush()
            output.seek(0)

            if user.hash == None:
                user_object = User.objects.filter(pk=request.user.id)
                apostille = muterun_js('nem/apostille.js')
                if apostille.exitcode == 0:
                    transaction_hash = str(apostille.stdout)[2:-3]
                    print(transaction_hash)
                    if len(transaction_hash) <= 64:
                        user_object.update(hash=transaction_hash)

                else:
                    sys.stderr.write(str(apostille.stderr))

            response.write(output.read())

    else:
        messages.error(request, 'Finish Exams and Assessment Test first.')
        return redirect('/home')

    return response


@login_required
def view_apostille(request):
    """Generate pdf."""
    # Model data
    user = request.user
    user_results = Results.objects.filter(user_id=user.id)
    individual_result = user_results.first()
    grade = exam_scores = results = context = programs = None

    if user.assessment_done and user.exam_done and user.grades_done:
        try:
            grade = Grade.objects.filter(user=request.user).first()
        except ObjectDoesNotExist:
            grade = None

        def get_score(course):
            try:
                score = user.sitting_set.filter(quiz__title=course).first().current_score
            except (TypeError, AttributeError):
                score = ''
            return score

        GE_score = get_score(course='General Engineering')
        CE_score = get_score(course='Civil Engineering')
        ECE_score = get_score(course='Electronics Engineering')
        EE_score = get_score(course='Electrical Engineering')
        ME_score = get_score(course='Mechanical Engineering')
        exam_scores = [GE_score, CE_score, ECE_score, EE_score, ME_score]

        try:
            results_unsorted = []
            programs = []
            Civil_Engineering =  "{:.2%}".format(individual_result.CE_grades + individual_result.CE_assessment + individual_result.CE_exam)
            Electronics_Engineering =  "{:.2%}".format(individual_result.ECE_grades + individual_result.ECE_assessment + individual_result.ECE_exam)
            Electrical_Engineering =  "{:.2%}".format(individual_result.EE_grades + individual_result.EE_assessment + individual_result.EE_exam)
            Mechanical_Engineering =  "{:.2%}".format(individual_result.ME_grades + individual_result.ME_assessment + individual_result.ME_exam)
            results_unsorted.extend([Civil_Engineering, Electronics_Engineering, Electrical_Engineering, Mechanical_Engineering])
            results = sorted(results_unsorted, reverse=True)
            
            for i in range(len(results)):
                programs.append(str(retrieve_name(results[i]))[2:-2].replace("_", " "))
        except ObjectDoesNotExist:
            results = None

        if not user.program:
            print('test')
            id = User.objects.filter(pk=user.id).values_list('id',flat=True).first()
            obj = User.objects.get(pk=id)
            obj.program = programs[0]
            obj.program_value = results[0]
            obj.save()
            

        context = {"user": user, "grade": grade, "exam_scores": exam_scores, "results": results, "programs": programs}

        # Rendered
        html_string = render_to_string('results.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri())
        css = CSS('register/static/assets/bootstrap/css/foroutput.css')
        html.write_pdf('nem/results_pdf/' + 'PURSUE_results.pdf', stylesheets=[css], presentational_hints=True)
        result = html.write_pdf(stylesheets=[css], presentational_hints=True)
        filename = f"{user.username}_Recommendation.pdf"
        
        # Creating http response
        content = "inline; filename=%s" %(filename)
        response = HttpResponse(content_type='application/pdf;')
        response['Content-Disposition'] = content
        response['Content-Transfer-Encoding'] = 'binary'

        with tempfile.NamedTemporaryFile(delete=True) as output:
            output.write(result)
            output.flush()
            output.seek(0)

            if user.hash == None:
                user_object = User.objects.filter(pk=request.user.id)
                apostille = muterun_js('nem/apostille.js')
                if apostille.exitcode == 0:
                    transaction_hash = str(apostille.stdout)[2:-3]
                    print(transaction_hash)
                    if len(transaction_hash) <= 64:
                        user_object.update(hash=transaction_hash)

                else:
                    sys.stderr.write(str(apostille.stderr))

            response.write(output.read())

    else:
        messages.error(request, 'Finish Exams and Assessment Test first.')
        return redirect('/home')

    return response

@login_required
def generate_certificate(request):
    """Generate pdf."""
    # Model data
    user = request.user
    context = None

    if user.assessment_done and user.exam_done and user.grades_done and user.hash and user.program:

        context = {"user": user}

        # Rendered
        html_string = render_to_string('certificate.html', context)
        html = HTML(string=html_string, base_url=request.build_absolute_uri())
        css = CSS('register/static/assets/bootstrap/css/foroutput.css')
        html.write_pdf('nem/results_pdf/' + 'PURSUE_results.pdf', stylesheets=[css], presentational_hints=True)

register/templates/register/register.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}

<title>Register</title>
                            <div class="text-center">
                                <h4 class="text-dark mb-4">Create an Account!</h4>
                            </div>
                            <form method="POST" class="user">
                                {% csrf_token %}

                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{ form.first_name }}{{form.first_name.errors}}
                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.last_name }} {{form.last_name.errors}}
                                    </div>

                                </div>
                                <div class="form-group">

                                        {{ form.school }}
                                        {{ form.school.errors }}

                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{ form.email }}
                                        {{form.email.errors}}
                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.username }}
                                        {{form.username.errors}}
                                    </div>

                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">{{ form.password1 }}</div>
                                    <div class="col-sm-6">{{ form.password2 }}</div>
                                    <p style="margin-left: 15px ">
                                        {{form.password1.errors}}
                                        {{form.password2.errors}}</p>

                                </div><button class="btn btn-primary btn-block text-white btn-user" type="submit">Register Account</button>
                                <hr>
                            </form>

                            <div class="text-center"><a class="small" href=" /password_reset">Forgot Password?</a></div>
                            <div class="text-center"><a class="small" href=" /login ">Already have an account? Login!</a></div>


{% endblock %}

{#                                <div class="form-group row">#}
{#                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="id_first_name" placeholder="First Name" name="first_name" required>{{form.first_name.errors}}</div>#}
{#                                    <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="id_last_name" placeholder="Last Name" name="last_name" required>{{form.last_name.errors}}</div>#}
{#                                </div>#}
{#                                <div class="form-group row">#}
{#                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="email" id="id_email" aria-describedby="emailHelp" placeholder="Email Address" name="email" required> {{form.email.errors}}</div>#}
{#                                    <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="id_username" placeholder="Username" name="username" required>{{form.username.errors}}</div>#}
{##}
{#                                </div>#}
{#                                <div class="form-group row">#}
{#                                    <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="password" id="id_password1" placeholder="Password" name="password1" required></div>#}
{#                                    <div class="col-sm-6"><input class="form-control form-control-user" type="password" id="id_password2" placeholder="Repeat Password" name="password2" required></div>#}
{#                                    <p style="margin-left: 15px ">#}
{#                                        {{form.password1.errors}}#}
{#                                        {{form.password2.errors}}</p>#}