core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from register import views as v
from quiz import views 


urlpatterns = [
#ADMIN AND HOME URLS
    path('admin/', admin.site.urls),
    path('login/', v.login, name='login'),
    path("", views.home, name = "home"),
    path('', include('django.contrib.auth.urls')),
    path("home/",views.home, name = "home"),
    path("about/",views.about, name = "about"),
    path("faq/",views.faq, name = "faq"),
    path("progs/",views.progs, name = "progs"),
    path("howto/",views.howto, name = "howto"),
    path("privacy/",views.privacy, name = "privacy"),
    path("terms/",views.terms, name = "terms"),
    path("output/",views.output, name = "output"),
    path("pursueproject/",views.pursueproject, name = "pursueproject"),
    path('pdf/', v.generate_apostille, name='generate_pdf'),
    path('view/pdf/', v.view_apostille, name='view_pdf'),
    path('certificate/', v.generate_certificate, name='generate_certificate'),
    path('view/certificate/', v.view_certificate, name='view_certificate'),


#PROGS
    path("progs/CE",views.CE, name = "CE"),
    path("progs/ECE",views.ECE, name = "ECE"),
    path("progs/ME",views.ME, name = "ME"),
    path("progs/EE",views.EE, name = "EE"),



#PROFILE URLS
    path("register/", v.register, name = "register"),
    path("profile/<str:pk>/", v.profile, name = "profile"),
    path("results/<str:pk>/", v.results, name = "results"),
    path("profile/edit/<str:pk>/", v.edit, name = "edit"),


#PASSWORD URLS
    path("password/", v.change_password, name = 'change_password'),

    path("password_reset/",auth_views.PasswordResetView.as_view(
        template_name = 'password_reset_form.html', 
        success_url = reverse_lazy("password_reset_done"),
        email_template_name = 'password_reset_email.html'),
        name = "password_reset"),
    
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name = 'registration/password_reset_done.html'),
        name = "password_reset_done"),

    path("password_reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name = 'registration/password_reset_confirm.html',
        success_url = reverse_lazy("password_reset_complete")), 
        name = "password_reset_confirm"),

    # path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='password_reset_confirm.html'),
    #     name="password_reset_confirm"),

    path("password_reset/complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name = 'registration/password_reset_complete.html'),
        name = "password_reset_complete"),

#python -m smtpd -n -c DebuggingServer localhost:1025
##^this is for setting up the email server for password reset, run in a separate workspace

#QUIZ URL
    path(r'exam/', include('quiz.urls')),

#INPUT GRADES URL
    path('', include('inputshs.urls')),
    

#ASSESSMENT URL
    path('', include('likert.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .validators import alphabetic

class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(_('first name'), max_length=150, blank=True, validators=[alphabetic])
    last_name = models.CharField(_('last name'), max_length=150, blank=True, validators=[alphabetic])
    date_created = models.DateTimeField(auto_now_add = True)
    grades_done = models.BooleanField(default=False)
    exam_done = models.BooleanField(default=False)
    assessment_done = models.BooleanField(default=False)
    email = models.EmailField(unique=True)
    hash = models.CharField(null=True, blank=True, max_length=64)
    program = models.CharField(null=True, blank=True, max_length=64)
    program_value = models.CharField(null=True, blank=True, max_length=64)
    school = models.CharField(null=True, blank=True, max_length=64)

class Results(models.Model):
    user = models.ForeignKey(User, related_name = 'results', on_delete = models.CASCADE)
    CE_grades = models.FloatField(default=0,  null=True, blank=True)
    ECE_grades = models.FloatField(default=0,  null=True, blank=True)
    EE_grades = models.FloatField(default=0,  null=True, blank=True)
    ME_grades = models.FloatField(default=0,  null=True, blank=True)
    
    GE_exam= models.FloatField(default=0,  null=True, blank=True)
    CE_exam= models.FloatField(default=0,  null=True, blank=True)
    ECE_exam = models.FloatField(default=0,  null=True, blank=True)
    EE_exam = models.FloatField(default=0,  null=True, blank=True)
    ME_exam = models.FloatField(default=0,  null=True, blank=True)

    GE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    CE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    ECE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    EE_exam_done = models.BooleanField(default=False, null=True, blank=True)
    ME_exam_done = models.BooleanField(default=False, null=True, blank=True)

    CE_assessment = models.FloatField(default=0,  null=True, blank=True)
    ECE_assessment = models.FloatField(default=0,  null=True, blank=True)
    EE_assessment = models.FloatField(default=0,  null=True, blank=True)
    ME_assessment = models.FloatField(default=0,  null=True, blank=True)
    
    class Meta:
            verbose_name_plural = ('Results')

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def result_create(sender, instance=None, created=False, **kwargs):
        if created:
            Results.objects.create(user=instance,)



#gawa ng custom user model na boolean field, if true ang "is done with test/grade/quiz", redirect to home

register/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate
from register.models import User
from django.forms.widgets import NumberInput
from inputshs import models


class RegisterForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'type':'text', 'placeholder':'Email Address'}),required = True)
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'type':'text', 'placeholder':'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'type':'password', 'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user', 'type': 'password', 'placeholder': 'Repeat Password'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'type': 'text', 'placeholder': 'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'type': 'text', 'placeholder': 'Last Name'}))
    school = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'type': 'text', 'placeholder': 'School'}))
    class Meta:
	    model = User    
	    fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "school",
            "password1",
            "password2",
            ]

    ###errors for email and username
    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("Email is already registered")
        return self.cleaned_data['email']

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    def clean_username(self):
        if User.objects.filter(username=self.cleaned_data['username']).exists():
            raise forms.ValidationError("Username is already in use")
        return self.cleaned_data['username']

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
        return user


#####################

# class LoginForm(AuthenticationForm):
#     remember_me = forms.BooleanField()  # and add the remember_me field


#Eto yung mga forms na pwede nila i edit sa future
class EditProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),required=False)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),required=False)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),required=False)
    school = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text'}),required=False)

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'school',
        }
        exclude = ('password',)

        def clean_email(self):    
            email = self.cleaned_data["email"]
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError('A user with that email already exists.')
            return email.lower()

        def clean_username(self):
            username = self.cleaned_data['username']
            if User.objects.exclude(pk=self.instance.pk).filter(username=username).exists():
                raise forms.ValidationError(u'Username "%s" is already in use.' % username)
            return username

        def save(self, commit=True):
            user = super(EditProfileForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            user.username = self.cleaned_data['username']
            if commit:
                user.save()
            return user

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'type':'password', 'placeholder': 'Old Password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'type':'password', 'placeholder': 'New Password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'type':'password', 'placeholder': 'Confirm New Password'}))

    class Meta:
        model = User
        fields = {
            'old_password',
            'new_password1',
            'new_password2',
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'type':'text', 'placeholder':'Enter Username ...'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'type':'password', 'placeholder':'Password'}))

    class Meta:
        model = User
        fields = {
            'username',
            'password',
        }

register/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <link rel="stylesheet" href=" {% static 'assets/bootstrap/css/bootstrap.min2.css' %} ">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{% static 'assets/css/untitled.css' %} ">
</head>

<body class="bg-gradient-primary">
  <div class="container">
        <div class="card shadow-lg o-hidden border-0 my-5">
            <div class="card-body p-0" >
                <div class="row" >
                    <div class="col-lg-5 d-none d-lg-flex">
                        <div class="flex-grow-1 bg-login-image" style="background-image: url( {% static 'assets/img/12.png' %} );background-size: 75%;background-repeat: no-repeat;"></div>
                    </div>
                    <div class="col-lg-7">
                                <div class="p-5">
{% block content %}

{% endblock %}
                                </div>
                    </div>
                </div>
            </div>
        </div>
  </div>

    <script src=" {% static 'assets/js/jquery.min2.js' %} "></script>
    <script src=" {% static 'assets/bootstrap/js/bootstrap.min2.js' %} "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src=" {% static 'assets/js/theme2.js' %} "></script>
</body>
</html>

register/templates/certificate.html
<!doctype html>
{% load static %}
<html lang="en">
<title> Certificate </title>
<link rel="stylesheet" href="{% static 'assets/bootstrap/css/foroutput.css' %}">

<div class="container">

    <img src="{% static 'assets/img/nem.png' %}" style="float: left" height="80px" alt="">

                <a href="/home">
                    <img src="{% static 'assets/img/12.png' %}" style="float: right; padding-right: 25px" height="100px" alt="">
                </a></div><br><br><br><br>
<hr style="height: 5px; background-color: #1b89e0; border-radius: 40%">

<div class="container" style="padding: 40px">
    <h4 style="text-align: justify;text-indent: 80px">    This is to certify that the recommendation for <strong>{{user.first_name|title}} {{user.last_name|title}}</strong> from
        <strong>{{user.school}}</strong> is authenticated with Blockchain notarization via NEM Apostille.
    </h4><br><h4 style="text-indent: 80px">The recommendation and the unique Hash key is:<br><br></h4>
    <div class="jumbotron" style="text-align: center">
    <h2>
        <strong>{{user.program}}: {{user.program_value}}</strong><br> <br></h2><h4>
        HASH Key: </h4><br><h5> {{user.hash}}
    </h5>
</div>
    </div>
<hr style="height: 5px; background-color: #1b89e0; border-radius: 40%">
<img src="{% static 'assets/img/nem logo.png' %}" style="float: left " height="150px" alt="">
<img src="{% static 'assets/img/apostille seal.png' %}" style="float: right" height="150px" alt="">


</html>

register/templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Change Password
{% endblock %}
{% block content %}
<div class="container">
<div class="block-heading" >
<h1 style="color: rgb(255,255,255);">Password Reset</h1>
<div class = "block-content">

    <form method = "POST" class="user">
        {% csrf_token %}
        {% include 'message.html' %}
        <small id="hint_id_new_password1" class="form-text text-muted">
            <ul style="text-align: left">
                <li>Your password can’t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be a commonly used password.</li>
                <li>Your password can’t be entirely numeric.</li>
            </ul>
        </small><br>
        {{ form.old_password }}
        {{form.old_password.errors}}
        <br>
        {{ form.new_password1 }}
        {{form.new_password1.errors}}
        <br>
        {{ form.new_password2 }}
        {{form.new_password2.errors}}
        <br>

    <button class="btn btn-primary text-white btn-user" type="submit">Change Password</button><a class="btn btn-light btn-outline-secondary" href="{% url 'edit' user.id %}">Cancel</a>

    </form>
    {{ form.non_field_errors }}
    <br>
</div></div></div>

{% endblock %}

{#{{ form.errors }}#}
{#        <small id="hint_id_new_password1" class="form-text text-muted">#}
{#            <ul style="text-align: left">#}
{#                <li>Your password can’t be too similar to your other personal information.</li>#}
{#                <li>Your password must contain at least 8 characters.</li>#}
{#                <li>Your password can’t be a commonly used password.</li>#}
{#                <li>Your password can’t be entirely numeric.</li>#}
{#            </ul>#}
{#        </small><br>#}
{##}
{#        <div><input type="password" name="old_password" autocomplete="current-password" autofocus="" placeholder="Old Password" class="textinput textInput form-control" required="" id="id_old_password"></div>#}
{#        {{form.old_password.errors}}#}
{#        <br>#}
{#        <div><input class="form-control form-control-user" type="password" id="id_new_password1" placeholder="New Password" name="new_password1" required="" autocomplete="new-password" ></div>#}
{#        {{form.new_password1.errors}}#}
{#        <br>#}
{##}
{#        <div><input class="form-control form-control-user" type="password" id="id_new_password2" placeholder="Confirm New Password" name="new_password2" required="" autocomplete="new-password" ></div>#}
{#        {{form.new_password2.errors}}#}
{#        <br>#}
{##}
{#        <br>#}

register/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile Edit {% endblock title %}
{% block content %}



            <div class="container">
                <div class="block-heading">
                    <div class="card shadow mb-3">
                        <div class="card-header py-3">
                            <h3 class="text-primary m-0 font-weight-bold" style="text-align: left;">User Settings</h3>
                        </div>
                        <div class="card-body">
                        {% include 'message.html' %}
                            <form method = "POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col">
                                        <div class="form-group"><label for="username" style="text-align: left;"><strong>Username</strong></label>
                                            {{ form.username }}
                                            {{form.username.errors}}
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="form-group"><label for="email"><strong>Email Address</strong></label>
                                            {{ form.email }}
                                            {{form.email.errors}}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-3">
                                        <div class="form-group"><label for="first_name"><strong>First Name</strong></label>
                                            {{ form.first_name }}
                                            {{form.first_name.errors}}
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group"><label for="last_name"><strong>Last Name</strong></label>
                                            {{ form.last_name }}
                                            {{form.last_name.errors}}
                                        </div>
                                    </div>
                                <div class="col-md-6">
                                        <div class="form-group"><label for="school"><strong>School</strong></label>
                                            {{ form.school }}
                                            {{form.school.errors}}
                                        </div>
                                    </div>
                                </div>



                                <div class="form-group" style="margin-bottom: -20px"><button class="btn btn-primary" type="submit">Save Settings</button></div>


                            </form><div class="form-group"><a href="{% url 'change_password' %}"/> <button class="btn-primary btn">Change Password</button></div>


                        </div>
                    </div>
                </div>
            </div>
        <section class="clean-block features">
            <div class="container">
                <div class="block-heading"></div>
            </div>
        </section>


{% endblock %}